name: Cloud Native Community Group (CNCG) Chapter Request
description: Request to create a new Cloud Native Community Group chapter in your city
title: "[Group Request] Create a new chapter"
body:
- type: markdown
  attributes:
    value: |
      ### Please Read:
      
      :loudspeaker: Prior to filling out the form below, please check [community.cncf.io](https://community.cncf.io) to confirm there isn't an active chapter in your area. If there is an active chapter, we recommend collaborating with the current organizers. You can also [file an organizer issue here](https://github.com/cncf/communitygroups/issues/new?assignees=&labels=&projects=&template=organizer-request.yml&title=%5BOrganizer+Request%5D+Add+or+Remove+Organizer+Name). :loudspeaker:

      Additionally, check all [open issues](https://github.com/cncf/communitygroups/issues) to ensure there isn't an open request. If there is an open ticket, please comment within that GitHub issue expressing your interest in co-organizing.
      
      If you have checked all the above and there are no active chapters or open GitHub issues, please fill out this form for our team to review.
- type: input
  id: name
  attributes:
    label: City or location name for your CNCG
    description: "If you recently had a chapter deactivated, please do not fill out this form; instead, reach out to community-groups@cncf.io."
    placeholder: e.g. Cloud Native San Francisco
  validations:
    required: true
- id: location
  type: input
  attributes:
    label: What country do you want to start your community group in?
    placeholder: e.g. United States
  validations:
    required: true
- id: organizer_1
  type: textarea
  attributes:
    label: Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, CNCF Slack workspace name (or if you need to be invited), and your required profile link on community.cncf.io
    placeholder: e.g. Audra Montenegro, CNCF, https://github.com/AudMonte01, https://www.linkedin.com/in/audramontenegro/, Audra Montenegro in CNCF Slack, https://community.cncf.io/u/m8bqcv/#/about
  validations:
    required: true
- id: organizer_2
  type: textarea
  attributes:
    label: Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, CNCF Slack workspace name (or if they need to be invited), and their required profile link on community.cncf.io
    placeholder: e.g. Audra Montenegro, CNCF, https://github.com/AudMonte01, https://www.linkedin.com/in/audramontenegro/, Audra Montenegro in CNCF Slack, https://community.cncf.io/u/m8bqcv/#/about
  validations:
    required: false
- id: organizer_3
  type: textarea
  attributes:
    label: Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, CNCF Slack workspace name (or if they need to be invited), and their required profile link on community.cncf.io
    placeholder: e.g. Audra Montenegro, CNCF, https://github.com/AudMonte01, https://www.linkedin.com/in/audramontenegro/, Audra Montenegro in CNCF Slack, https://community.cncf.io/u/m8bqcv/#/about
  validations:
    required: false
- id: meetupDOTcom
  type: textarea
  attributes:
    label: If you already run a meetup, please link it here
    placeholder: e.g. https://www.meetup.com/bay-area-kubernetes-meetup/
  validations:
    required: false
- id: content
  type: textarea
  attributes:
    label: What is your mission statement or objective for this new chapter?
    placeholder: e.g. We’re excited about microservices, containers, the distributions that run them, and the solutions that deploy, manage, and extend them. Any skill level is welcome; we’re all new to Kubernetes, and we want to create an open, welcoming environment for other Kubernauts.
  validations:
    required: true
- id: organizer_coc
  type: checkboxes
  attributes:
    label: Code of Conduct
    description: "The Code of Conduct helps create a safe space for everyone. We require everyone to agree to it, including any and all future speakers and future co-organizers."
    options:
      - label: I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)
        required: true
- id: organizer_residency
  type: checkboxes
  attributes:
    label: Where organizers reside
    description: "All CNCG organizers must live in the area where they are seeking to host a chapter. The above-mentioned location must be where you reside full time."
    options:
      - label: I/We confirm I/we am/are local to, or live near, the city of the above-proposed chapter.
        required: true
- id: organizer_affiliation
  type: checkboxes
  attributes:
    label: Organizers' companies/affiliations
    description: "Not all CNCG organizers can be from the same company."
    options:
      - label: I/We agree that if there is more than one organizer now or onboarded in the future, the majority will come from different companies.
        required: true
- id: organizer_inclusivity
  type: checkboxes
  attributes:
    label: Inclusive
    description: "You agree to be inclusive of all people eager to learn about cloud native, regardless of their level of expertise in their open source journey."
    options:
      - label: I/We agree. To ensure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
        required: true
- id: organizer_neutrality
  type: checkboxes
  attributes:
    label: Vendor neutral
    description: "CNCGs should have vendor-neutral content for the main portion of your meetups. Please note that [sponsors can have up to 15 minutes on stage](https://github.com/cncf/communitygroups/blob/main/best_practices.md#sponsorships)."
    options:
      - label: I/We have read what [vendor neutrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/) and agree that the main content of our meetups will remain vendor-neutral.
        required: true
- id: organizer_branding
  type: checkboxes
  attributes:
    label: Agree to use CNCG branding
    description: "In an effort to avoid trademark misuse and maintain unity within the CNCG program, you agree to use [CNCG branding](https://github.com/cncf/artwork/blob/main/examples/other.md#cloud-native-community-groups)."
    options:
      - label: I/We agree to use the CNCG logo in my/our chapter and social branding.
        required: true
- id: organizer_registration
  type: checkboxes
  attributes:
    label: Registration through CNCF platforms
    description: "In order to properly support your chapter with benefits, registration for your meetups must be through CNCF platforms, or the current CNCF community platform."
    options:
      - label: I/We agree to host free registration on the main CNCF platform.
        required: true
- id: organizer_activity
  type: checkboxes
  attributes:
    label: Remain an active chapter
    description: "You agree to host a meetup, study group, or virtual event [at least once every 90 days (quarter)](https://github.com/cncf/communitygroups/blob/main/README.md#community-group-inactivity). If you foresee a delay, you will notify the CNCF team via community-groups@cncf.io."
    options:
      - label: I/We agree to have a meetup at least once every 90 days, or else communicate the reasoning for upcoming inactivity.
        required: true
- id: organizer_collaboration
  type: checkboxes
  attributes:
    label: Collaboration with other chapters
    description: "CNCF has the right to approve additional chapters in your location if you live in a significantly populous area."
    options:
      - label: I/We acknowledge CNCF's right to approve additional chapters in my area based on this criteria.
        required: true
- id: organizer_diversity
  type: checkboxes
  attributes:
    label: Aim to have a diverse representation of speakers in your meetups
    description: "Diversity means something different in each country. The common goal across all countries is to strive to promote women and other non-male speakers."
    options:
      - label: I/We will do our best to host diverse speakers throughout the year.
        required: true
- type: markdown
  attributes:
    value: |
      ### Review Time

      Review of your chapter request may take up to 30 days while our team performs due diligence. If you have questions during the process, please comment within your GitHub issue.
